version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authlab
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: 
      context: .
      dockerfile: ./backend/API/Dockerfile
    container_name: backend
    ports:
      - "7063:7063" 
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_URLS=http://+:7063
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=authlabdb;user=root;password=Pks10@2166;
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"  
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
